# Generated by Django 6.0.3 on 2026-03-27 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('website', 'Website'), ('whatsapp', 'WhatsApp')], default='website', max_length=20)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('whatsapp_user_id', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('user_name', models.CharField(blank=True, max_length=150)),
                ('user_phone', models.CharField(blank=True, max_length=40)),
                ('lead_service', models.CharField(blank=True, max_length=120)),
                ('suburb', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_lead', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.chatconversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
